version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: facilita_juridico_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: facilita_juridico
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql 

volumes:
  postgres-data:
    driver: local
